os: linux

dist: xenial

sudo: required

addons:
  apt:
    packages:
    - lcov
    - astyle
    - devscripts
    - python3
    - python3-pip
    - python3-dev
    - python-autopep8
    - doxygen
    - fakeroot
    - debhelper
    - pkg-config
    - alien
    - rpm
    - dh-make
    - dh-golang

install:
  - gem install coveralls-lcov

matrix:
  include:
    - language: c
      script:
        - make c
      #after_success:
      #  - coveralls-lcov /home/travis/build/nexmoinc/numkey/c/target/test/coverage/numkey.info
    - language: go
      script:
        - make go
    - language: python
      script:
        - make python
    - language: node_js
      node_js:
        - "7"
      install:
        - npm install --global uglify-js js-beautify
      script:
        - make javascript
      
